#!/bin/bash

echo ""
echo "______________"
echo ""
bash ./mac/scripts/01_homebrew.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/02_git.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/03_ssh_key.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/04_fonts.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/05_zsh.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/06_js.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/07_go.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/08_flutter.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/09_docker.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/10_code_editors.sh
echo ""
echo "______________"
echo ""
bash ./mac/scripts/11_terminal_apps.sh
echo ""
echo "______________"
echo ""
#bash ./mac/scripts/12_ai_agents.sh
echo ""
echo "______________"
echo ""
#bash ./mac/scripts/13_gui_apps.sh